---
# tasks file for roles/kvm
- name: install kvm and dependencies
  apt:
    name:
      - qemu-kvm
      - libvirt-bin
      - bridge-utils
    state: present

- name: install ubuntu-vm-builder
  apt:
    name: ubuntu-vm-builder
    state: present

- name: ensure libvirtd group exists
  group:
    name: libvirtd
    state: present

- name: add user to libvirtd group
  user:
    name: "{{myuser}}"
    groups: libvirtd
    append: yes
