---
# tasks file for roles/elementary-plus
- name: add elementary-plus repo
  apt_repository:
    repo: ppa:cybre/elementaryplus
    update_cache: yes
- name: install elementaryplus
  apt:
    name: elementaryplus
    state: present
