---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Install common dependencies
    apt:
      name: '{{item}}'
      state: present
    with_items:
    - htop
    - powertop
    - tree
    - trash-cli
    - jq
    - nmap
    - ack-grep
