---
- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
  - name: Install common dependencies
    apt:
      name:
      - htop
      - powertop
      - tree
      - trash-cli
      - jq
      - nmap
      - ack-grep
      - traceroute
      - xsel # support pbcopy
      - xclip
      - xprintidle
      # - myrepos
      state: present

  - debug: var=ansible_codename
  - debug: var=ansible_lsb

- name: import bionic fixes
  import_playbook: bionic.yaml
  when: ansible_lsb.codename == "bionic" or ansible_lsb.codename == "juno"
