---
- hosts: all
  become: yes
  gather_facts: smart

  tasks:
  - name: Install common dependencies
    apt:
      name: '{{item}}'
      state: present
    with_items:
    - htop
    - powertop
    - tree
