---

- name: add flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpaks }}"
