---
# tasks file for roles/virtualbox
- name: install key
  # command: wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present  

- name: add repo
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian xenial contrib
    state: present
    update_cache: yes

- name: install virtualbox
  apt:
    name: virtualbox
    state: present
