---
# tasks file for roles/moka-icon-theme
- name: add moka repo
  apt_repository:
    repo:  ppa:moka/daily
    update_cache: yes
- name: install moka-icon-theme
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - moka-icon-theme
    - faba-icon-theme
    - faba-mono-icons