#!/bin/sh

# script/run: Run a playbook.

set -e

cd "$(dirname "$0")/.."

hostname="${1:-$(hostname)}"
username="$(whoami)"

ansible-playbook -i inventory "$hostname.yml" -K --limit "$hostname" --extra-vars "myuser=$username"
