---
# tasks file for roles/arc-theme
- name: add arc-theme soft-fork ppa
  apt_repository:
    repo: ppa:fossfreedom/arc-gtk-theme-daily
    update_cache: yes
- name: install arc-theme
  apt:
    name: arc-theme
    state: present

- stat:
    path: /usr/share/icons/Arc
  register: arc_icon_theme_folder

- include: arc-icon-theme.yml
  when: arc_icon_theme_folder.stat.exists == False
