---
# tasks file for roles/docker
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
    update_cache: yes

- apt:
    name: docker-ce
    state: present