---
# tasks file for roles/docker
- name: import docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
    update_cache: yes

- name: install docker-ce
  apt:
    name: docker-ce
    state: present

- name: add user to docker group
  user:
    name: "{{myuser}}"
    groups: docker
    append: yes