---
# tasks file for roles/docker
- name: import docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get upstream codename (bionic, xenial, trusty etc.)
  shell: lsb_release -cus || lsb_release -cs
  changed_when: false
  register: upstream_codename

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ upstream_codename.stdout_lines[0] }} stable
    state: present
    update_cache: yes

- name: install docker-ce
  apt:
    name: docker-ce
    state: present

- name: add user to docker group
  user:
    name: "{{myuser}}"
    groups: docker
    append: yes